In [11]:
import numpy as np

A = np.array([
    [3, 1],
    [1, 3]
], dtype=float)

print("Original Matrix:")
print(A)

Original Matrix:
[[3. 1.]
 [1. 3.]]


In [9]:
import numpy as np
from sklearn.datasets import load_iris

In [12]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ba0d05cb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# part A \n",
    "# SVD Implementation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "692b7526",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original Matrix:\n",
      "[[3. 1.]\n",
      " [1. 3.]]\n",
      "\n",
      "A^T A:\n",
      "[[10.  6.]\n",
      " [ 6. 10.]]\n",
      "\n",
      "Eigenvalues:\n",
      "[16.  4.]\n",
      "\n",
      "Eigenvectors:\n",
      "[[ 0.70710678 -0.70710678]\n",
      " [ 0.70710678  0.70710678]]\n",
      "\n",
      "Singular Values:\n",
      "[4. 2.]\n",
      "\n",
      "U:\n",
      "[[ 0.70710678 -0.70710678]\n",
      " [ 0.70710678  0.70710678]]\n",
      "\n",
      "S:\n",
      "[[4. 0.]\n",
      " [0. 2.]]\n",
      "\n",
      "V^T:\n",
      "[[ 0.70710678  0.70710678]\n",
      " [-0.70710678  0.70710678]]\n",
      "\n",
      "Reconstructed Matrix:\n",
      "[[3. 1.]\n",
      " [1. 3.]]\n",
      "\n",
      "Reconstruction Error:\n",
      "7.021666937153402e-16\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "# Given matrix\n",
    "A = np.array([\n",
    "    [3, 1],\n",
    "    [1, 3]\n",
    "], dtype=float)\n",
    "\n",
    "print(\"Original Matrix:\")\n",
    "print(A)\n",
    "\n",
    "# Step 1: Calculate A transpose A\n",
    "ATA = A.T @ A\n",
    "\n",
    "print(\"\\nA^T A:\")\n",
    "print(ATA)\n",
    "\n",
    "# Step 2: Find eigenvalues and eigenvectors\n",
    "eigenvalues, eigenvectors = np.linalg.eigh(ATA)\n",
    "\n",
    "# Sort in descending order\n",
    "index = np.argsort(eigenvalues)[::-1]\n",
    "\n",
    "eigenvalues = eigenvalues[index]\n",
    "eigenvectors = eigenvectors[:, index]\n",
    "\n",
    "print(\"\\nEigenvalues:\")\n",
    "print(eigenvalues)\n",
    "\n",
    "print(\"\\nEigenvectors:\")\n",
    "print(eigenvectors)\n",
    "\n",
    "# Step 3: Calculate singular values\n",
    "singular_values = np.sqrt(eigenvalues)\n",
    "\n",
    "print(\"\\nSingular Values:\")\n",
    "print(singular_values)\n",
    "\n",
    "# Step 4: Calculate U\n",
    "U = A @ eigenvectors\n",
    "\n",
    "for i in range(len(singular_values)):\n",
    "    U[:, i] = U[:, i] / singular_values[i]\n",
    "\n",
    "# S matrix\n",
    "S = np.diag(singular_values)\n",
    "\n",
    "# V transpose\n",
    "Vt = eigenvectors.T\n",
    "\n",
    "print(\"\\nU:\")\n",
    "print(U)\n",
    "\n",
    "print(\"\\nS:\")\n",
    "print(S)\n",
    "\n",
    "print(\"\\nV^T:\")\n",
    "print(Vt)\n",
    "\n",
    "# Step 5: Reconstruct A\n",
    "A_reconstructed = U @ S @ Vt\n",
    "\n",
    "print(\"\\nReconstructed Matrix:\")\n",
    "print(A_reconstructed)\n",
    "\n",
    "# Reconstruction error\n",
    "error = np.linalg.norm(A - A_reconstructed)\n",
    "\n",
    "print(\"\\nReconstruction Error:\")\n",
    "print(error)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e05830e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# part B \n",
    "# PCA Using SVD"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "557ab3bb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original Dataset Shape:\n",
      "(150, 4)\n",
      "\n",
      "Mean:\n",
      "[5.84333333 3.05733333 3.758      1.19933333]\n",
      "\n",
      "First 5 rows of centered data:\n",
      "[[-0.74333333  0.44266667 -2.358      -0.99933333]\n",
      " [-0.94333333 -0.05733333 -2.358      -0.99933333]\n",
      " [-1.14333333  0.14266667 -2.458      -0.99933333]\n",
      " [-1.24333333  0.04266667 -2.258      -0.99933333]\n",
      " [-0.84333333  0.54266667 -2.358      -0.99933333]]\n",
      "\n",
      "Singular Values:\n",
      "[25.09996044  6.01314738  3.41368064  1.88452351]\n",
      "\n",
      "Principal Components:\n",
      "[[ 0.36138659 -0.08452251  0.85667061  0.3582892 ]\n",
      " [-0.65658877 -0.73016143  0.17337266  0.07548102]\n",
      " [ 0.58202985 -0.59791083 -0.07623608 -0.54583143]\n",
      " [ 0.31548719 -0.3197231  -0.47983899  0.75365743]]\n",
      "\n",
      "Explained Variance Ratio:\n",
      "[0.92461872 0.05306648 0.01710261 0.00521218]\n",
      "\n",
      "Reduced Data:\n",
      "[[-2.68412563 -0.31939725]\n",
      " [-2.71414169  0.17700123]\n",
      " [-2.88899057  0.14494943]\n",
      " [-2.74534286  0.31829898]\n",
      " [-2.72871654 -0.32675451]\n",
      " [-2.28085963 -0.74133045]\n",
      " [-2.82053775  0.08946138]\n",
      " [-2.62614497 -0.16338496]\n",
      " [-2.88638273  0.57831175]\n",
      " [-2.6727558   0.11377425]]\n",
      "\n",
      "Reconstructed Data:\n",
      "[[5.08303897 3.51741393 1.40321372 0.21353169]\n",
      " [4.7462619  3.15749994 1.46356177 0.24024592]\n",
      " [4.70411871 3.1956816  1.30821697 0.17518015]\n",
      " [4.6422117  3.05696697 1.46132981 0.23973218]\n",
      " [5.07175511 3.52655486 1.36373845 0.19699991]]\n",
      "\n",
      "Reconstruction Error:\n",
      "0.025341073932398248\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from sklearn.datasets import load_iris\n",
    "\n",
    "# Load Iris dataset\n",
    "iris = load_iris()\n",
    "\n",
    "X = iris.data\n",
    "\n",
    "print(\"Original Dataset Shape:\")\n",
    "print(X.shape)\n",
    "\n",
    "# Step 1: Calculate mean\n",
    "mean = np.mean(X, axis=0)\n",
    "\n",
    "print(\"\\nMean:\")\n",
    "print(mean)\n",
    "\n",
    "# Step 2: Center the data\n",
    "X_centered = X - mean\n",
    "\n",
    "print(\"\\nFirst 5 rows of centered data:\")\n",
    "print(X_centered[:5])\n",
    "\n",
    "# Step 3: Apply SVD\n",
    "U, S, Vt = np.linalg.svd(X_centered, full_matrices=False)\n",
    "\n",
    "print(\"\\nSingular Values:\")\n",
    "print(S)\n",
    "\n",
    "# Step 4: Principal Components\n",
    "print(\"\\nPrincipal Components:\")\n",
    "print(Vt)\n",
    "\n",
    "# Step 5: Explained variance\n",
    "variance = S**2 / (len(X) - 1)\n",
    "\n",
    "explained_variance_ratio = variance / np.sum(variance)\n",
    "\n",
    "print(\"\\nExplained Variance Ratio:\")\n",
    "print(explained_variance_ratio)\n",
    "\n",
    "# Step 6: Reduce to 2 dimensions\n",
    "X_reduced = X_centered @ Vt[:2].T\n",
    "\n",
    "print(\"\\nReduced Data:\")\n",
    "print(X_reduced[:10])\n",
    "\n",
    "# Step 7: Reconstruct the data\n",
    "X_reconstructed = X_reduced @ Vt[:2] + mean\n",
    "\n",
    "print(\"\\nReconstructed Data:\")\n",
    "print(X_reconstructed[:5])\n",
    "\n",
    "# Step 8: Calculate reconstruction error\n",
    "error = np.mean((X - X_reconstructed) ** 2)\n",
    "\n",
    "print(\"\\nReconstruction Error:\")\n",
    "print(error)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

{'cells': [{'cell_type': 'code',
   'execution_count': 1,
   'id': 'ba0d05cb',
   'metadata': {},
   'outputs': [],
   'source': ['# part A \n', '# SVD Implementation']},
  {'cell_type': 'code',
   'execution_count': 2,
   'id': '692b7526',
   'metadata': {},
   'outputs': [{'name': 'stdout',
     'output_type': 'stream',
     'text': ['Original Matrix:\n',
      '[[3. 1.]\n',
      ' [1. 3.]]\n',
      '\n',
      'A^T A:\n',
      '[[10.  6.]\n',
      ' [ 6. 10.]]\n',
      '\n',
      'Eigenvalues:\n',
      '[16.  4.]\n',
      '\n',
      'Eigenvectors:\n',
      '[[ 0.70710678 -0.70710678]\n',
      ' [ 0.70710678  0.70710678]]\n',
      '\n',
      'Singular Values:\n',
      '[4. 2.]\n',
      '\n',
      'U:\n',
      '[[ 0.70710678 -0.70710678]\n',
      ' [ 0.70710678  0.70710678]]\n',
      '\n',
      'S:\n',
      '[[4. 0.]\n',
      ' [0. 2.]]\n',
      '\n',
      'V^T:\n',
      '[[ 0.70710678  0.70710678]\n',
      ' [-0.70710678  0.70710678]]\n',
      '\n',
      '