In [7]:
import numpy as np

In [9]:

# 1. Validate the Input System
def validate_system(A, b):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    if A.ndim != 2:
        raise ValueError("Coefficient matrix must be 2-dimensional.")

    rows, cols = A.shape

    if rows != cols:
        raise ValueError("Coefficient matrix must be square.")

    if b.ndim != 1 or len(b) != rows:
        raise ValueError("RHS vector dimensions do not match the matrix.")

    return A, b


# 2. Forward Elimination with Partial Pivoting
def forward_elimination(A, b, tolerance=1e-12):

    A, b = validate_system(A, b)

    n = len(b)

    augmented = np.column_stack((A, b))

    print("\nAugmented Matrix:")
    print(np.round(augmented, 4))

    
    for i in range(n):

        
        pivot_row = i + np.argmax(
            np.abs(augmented[i:, i])
        )
        if abs(augmented[pivot_row, i]) < tolerance:
            raise ValueError(
                "Singular matrix or system without a unique solution."
            )
        if pivot_row != i:
            augmented[[i, pivot_row]] = \
                augmented[[pivot_row, i]]
        for j in range(i + 1, n):

            factor = (
                augmented[j, i] /
                augmented[i, i]
            )

            augmented[j, i:] -= (
                factor * augmented[i, i:]
            )

        # Display matrix after each step
        print(f"\nAfter eliminating column {i + 1}:")
        print(np.round(augmented, 4))

    return augmented

# 3. Back Substitution
def back_substitution(augmented, tolerance=1e-12):

    n = augmented.shape[0]

    x = np.zeros(n)

    for i in range(n - 1, -1, -1):

        pivot = augmented[i, i]

        if abs(pivot) < tolerance:
            raise ValueError(
                "Zero pivot encountered during back substitution."
            )

        known_terms = np.dot(
            augmented[i, i + 1:n],
            x[i + 1:n]
        )

        x[i] = (
            augmented[i, n] - known_terms
        ) / pivot

    return x


# 4. Gaussian Elimination
def gaussian_elimination(A, b):

    # Step 1: Forward elimination
    augmented = forward_elimination(A, b)

    # Step 2: Back substitution
    solution = back_substitution(augmented)

    return solution


# 5. Verify the Solution
def verify_solution(A, b, x, tolerance=1e-8):

    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)

    # Calculate A × x
    calculated_b = A @ x

    print("\nVerification:")
    print("A x =", np.round(calculated_b, 6))
    print("b   =", np.round(b, 6))

    if np.allclose(
        calculated_b,
        b,
        atol=tolerance
    ):
        print("Verification successful: A x = b")
        return True

    print("Verification failed.")
    return False


# 6. Display System
def display_system(A, b):

    print("\nCoefficient Matrix A:")
    print(np.array(A, dtype=float))

    print("\nRHS Vector b:")
    print(np.array(b, dtype=float))


# 7. Solve a System
def solve_example(number, A, b):

    print("\n" + "=" * 60)
    print(f"SYSTEM {number}")
    print("=" * 60)

    try:

        # Display input
        display_system(A, b)

        # Solve system
        solution = gaussian_elimination(A, b)

        # Display solution
        print("\nSolution:")

        for i, value in enumerate(solution):
            print(f"x{i + 1} = {value:.6f}")

        # Verify solution
        verify_solution(A, b, solution)

    except ValueError as error:

        print("\nError:", error)

# 8. Main Function
def main():
    # SYSTEM 1
    #
    # 2x + y - z  = 8
    # -3x - y + 2z = -11
    # -2x + y + 2z = -3
    #
    # Solution:
    # x = 2, y = 3, z = -1

    A1 = [
        [2, 1, -1],
        [-3, -1, 2],
        [-2, 1, 2]
    ]

    b1 = [
        8,
        -11,
        -3
    ]

    solve_example(1, A1, b1)


    
    # SYSTEM 2
    #
    # x + y + z = 6
    # 2x + 3y + z = 10
    # x + 2y + 3z = 13
    #
    # Solution:
    # x = 2, y = 1, z = 3
    

    A2 = [
        [1, 1, 1],
        [2, 3, 1],
        [1, 2, 3]
    ]

    b2 = [
        6,
        10,
        13
    ]

    solve_example(2, A2, b2)

if __name__ == "__main__":
    main()


SYSTEM 1

Coefficient Matrix A:
[[ 2.  1. -1.]
 [-3. -1.  2.]
 [-2.  1.  2.]]

RHS Vector b:
[  8. -11.  -3.]

Augmented Matrix:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

After eliminating column 1:
[[ -3.      -1.       2.     -11.    ]
 [  0.       0.3333   0.3333   0.6667]
 [  0.       1.6667   0.6667   4.3333]]

After eliminating column 2:
[[ -3.      -1.       2.     -11.    ]
 [  0.       1.6667   0.6667   4.3333]
 [  0.       0.       0.2     -0.2   ]]

After eliminating column 3:
[[ -3.      -1.       2.     -11.    ]
 [  0.       1.6667   0.6667   4.3333]
 [  0.       0.       0.2     -0.2   ]]

Solution:
x1 = 2.000000
x2 = 3.000000
x3 = -1.000000

Verification:
A x = [  8. -11.  -3.]
b   = [  8. -11.  -3.]
Verification successful: A x = b

SYSTEM 2

Coefficient Matrix A:
[[1. 1. 1.]
 [2. 3. 1.]
 [1. 2. 3.]]

RHS Vector b:
[ 6. 10. 13.]

Augmented Matrix:
[[ 1.  1.  1.  6.]
 [ 2.  3.  1. 10.]
 [ 1.  2.  3. 13.]]

After eliminating column 1:
[[ 2. 